// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AISelect(arg1:Array<any>,arg2:number,arg3:number):Promise<main.AISelectResult>;
